name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install uv
        
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --group dev
        
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/
